version: "3.8"

networks:
  library-network:
    name: library-network
    driver: bridge

services:
  db:
    image: postgres:15.1-alpine
    hostname: postgres
    restart: always
    networks:
      - library-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  library-system:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - library-network
    depends_on:
      - db
    ports:
      - "8080:8080"
    expose:
      - "8080"

  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    restart: always
    networks:
      - library-network

  grafana:
    image: grafana/grafana-oss:9.1.4
    user: "$UID:$GID"
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - library-network
